# Standard SBT Example Workflow (almost)
name: CI
on:
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false

      matrix:
        include:
         - os: ubuntu-latest
           java: 8
         - os: ubuntu-latest
           java: 11
    runs-on: ${{ matrix.os }}

    env:
       JAVA_OPTS: -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
       JVM_OPTS : -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       IS_CI: "true"

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}

      - name: Coursier cache
        uses: coursier/cache-action@v6

      - name: Build and Test
        run: sbt -v +test

      - name: Cleanup before cache
        shell: bash
        run: |
          rm -rf "$HOME/.ivy2/local" || true
          find $HOME/Library/Caches/Coursier/v1        -name "ivydata-*.properties" -delete || true
          find $HOME/.ivy2/cache                       -name "ivydata-*.properties" -delete || true
          find $HOME/.cache/coursier/v1                -name "ivydata-*.properties" -delete || true
          find $HOME/.sbt                              -name "*.lock"               -delete || true
